name: phamijam
description: "A new Flutter project."
publish_to: "none"
version: 1.1.2+1

environment:
  sdk: ^3.12.2

dependencies:
  another_flushbar: ^2.2.4
  app_links: ^7.2.1
  audio_service: ^0.18.19
  audio_video_progress_bar: ^2.0.3
  cached_network_image: ^3.4.1
  cloud_firestore: ^6.0.0
  crypto: ^3.0.6
  firebase_auth: ^6.5.6
  firebase_core: ^4.12.1
  flutter:
    sdk: flutter
  flutter_dotenv: ^6.0.1
  google_sign_in_all_platforms: ^2.0.3
  home_widget: ^0.9.3
  http: ^1.4.0
  just_audio: ^0.10.6
  marquee: ^2.3.0
  path_provider: ^2.1.5
  provider: ^6.1.5+1
  share_plus: ^13.3.0
  shared_preferences: ^2.3.3
  sign_in_with_apple: ^7.0.1
  url_launcher: ^6.3.1
  video_player: ^2.13.0
  youtube_explode_dart: ^3.1.0
  ytmusicapi_dart: ^2.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.4
  flutter_native_splash: ^2.4.8

dependency_overrides:
  path_provider_android: 2.2.17

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/p-trans.png"
  image_path_android: "assets/images/P.jpg"
  image_path_ios: "assets/images/P.jpg"
  remove_alpha_ios: true
  adaptive_icon_background: "#DBA43A"
  adaptive_icon_foreground: "assets/images/p-trans.png"
  image_path_ios_dark_transparent: "assets/images/p-trans.png"
  image_path_ios_tinted_grayscale: "assets/images/p-trans.png"
  desaturate_tinted_to_grayscale_ios: true

flutter_native_splash:
  color: "#DBA43A"
  image: "assets/images/p-trans.png"
  color_dark: "#1C1B1A"
  image_dark: "assets/images/p-trans.png"

  fullscreen: true

  android_12:
    image: "assets/images/p-trans.png"
    color: "#DBA43A"
    image_dark: "assets/images/p-trans.png"
    color_dark: "#1C1B1A"

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/CHANGELOG.md
    - .env
  fonts:
    - family: Lexend
      fonts:
        - asset: assets/fonts/Lexend-Regular.ttf
